/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Ic_emoji: typeof import('./components/icons/ic_emoji.vue')['default']
    Ic_image: typeof import('./components/icons/ic_image.vue')['default']
    Ic_movie: typeof import('./components/icons/ic_movie.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}

// For TSX support
declare global {
  const Accordion: typeof import('primevue/accordion')['default']
  const AccordionTab: typeof import('primevue/accordiontab')['default']
  const Avatar: typeof import('primevue/avatar')['default']
  const Badge: typeof import('primevue/badge')['default']
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const Ic_emoji: typeof import('./components/icons/ic_emoji.vue')['default']
  const Ic_image: typeof import('./components/icons/ic_image.vue')['default']
  const Ic_movie: typeof import('./components/icons/ic_movie.vue')['default']
  const InputGroup: typeof import('primevue/inputgroup')['default']
  const InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Message: typeof import('primevue/message')['default']
  const PanelMenu: typeof import('primevue/panelmenu')['default']
  const Password: typeof import('primevue/password')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TabPanel: typeof import('primevue/tabpanel')['default']
  const TabView: typeof import('primevue/tabview')['default']
  const Textarea: typeof import('primevue/textarea')['default']
}